from pathlib import Path

import pandas as pd
import streamlit as st


PROJECT_ROOT = Path(__file__).resolve().parents[2]

SEARCH_DIRECTORIES = [
    PROJECT_ROOT / "data",
    PROJECT_ROOT / "datasets",
    PROJECT_ROOT / "features",
    PROJECT_ROOT / "results",
]


st.title("Data and Results Explorer")

st.markdown(
    """
Explore datasets, engineered features, model outputs, and backtesting results
generated by the research notebooks.
"""
)


@st.cache_data
def find_csv_files(directories: list[Path]) -> list[Path]:
    files = []

    for directory in directories:
        if directory.exists():
            files.extend(directory.rglob("*.csv"))

    return sorted(set(files))


@st.cache_data
def load_csv(path: Path) -> pd.DataFrame:
    return pd.read_csv(path)


csv_files = find_csv_files(SEARCH_DIRECTORIES)

if not csv_files:
    st.warning(
        "No CSV files were found in data, datasets, features, or results."
    )
    st.stop()


relative_paths = {
    str(path.relative_to(PROJECT_ROOT)): path
    for path in csv_files
}

selected_name = st.selectbox(
    "Choose a file",
    options=list(relative_paths.keys()),
)

selected_path = relative_paths[selected_name]

try:
    df = load_csv(selected_path)
except Exception as exc:
    st.error(f"Could not load the selected file: {exc}")
    st.stop()


col1, col2, col3 = st.columns(3)

col1.metric("Rows", f"{len(df):,}")
col2.metric("Columns", len(df.columns))
col3.metric(
    "Missing Values",
    f"{int(df.isna().sum().sum()):,}",
)

st.subheader("Preview")

st.dataframe(
    df.head(200),
    use_container_width=True,
    hide_index=True,
)

st.subheader("Column Information")

column_info = pd.DataFrame(
    {
        "Column": df.columns,
        "Data Type": [str(dtype) for dtype in df.dtypes],
        "Missing": df.isna().sum().values,
        "Unique Values": [
            df[column].nunique(dropna=True)
            for column in df.columns
        ],
    }
)

st.dataframe(
    column_info,
    use_container_width=True,
    hide_index=True,
)

numeric_columns = df.select_dtypes(include="number").columns.tolist()

if numeric_columns:
    st.subheader("Numeric Visualization")

    selected_column = st.selectbox(
        "Choose a numeric column",
        numeric_columns,
    )

    st.line_chart(df[selected_column])